#!/usr/bin/env python
#
##############################################################################
#
# MODULE:       model
#
# AUTHOR(S):    will
#               
# PURPOSE:      Script generated by wxGUI Graphical Modeler.
#
# DATE:         Fri Jun 24 09:33:39 2016
#
##############################################################################

#%module
#% description: Script generated by wxGUI Graphical Modeler.
#%end

import sys
import os
import atexit

from grass.script import parser, run_command

def cleanup():
    pass

def main():
    run_command("v.net",
                flags = 'c',
                input = "b10s_s100@will",
                output = "b10s_net",
                operation = "nodes",
                arc_layer = "1",
                node_layer = "2")

    run_command("v.net.allpairs",
                input = "b10s_net",
                output = "b10s_ap",
                arc_layer = "1",
                node_layer = "2",
                arc_column = "len")


    return 0

if __name__ == "__main__":
    options, flags = parser()
    atexit.register(cleanup)
    sys.exit(main())
