#!/usr/bin/env python
#
##############################################################################
#
# MODULE:       model
#
# AUTHOR(S):    will
#               
# PURPOSE:      Script generated by wxGUI Graphical Modeler.
#
# DATE:         Fri Jun 24 09:15:29 2016
#
##############################################################################

#%module
#% description: Script generated by wxGUI Graphical Modeler.
#%end

import sys
import os
import atexit

from grass.script import parser, run_command

def cleanup():
    pass

def main():

    run_command("v.extract",
                input = "snp_shed1@will",
                layer = "1",
                type = "point,line,boundary,centroid,area,face",
                cats = "2",
                output = "b10",
                new = -1)

    run_command("v.select",
                ainput = "elevs_stream@will",
                alayer = "1",
                atype = "point,line,area",
                binput = "b10",
                blayer = "1",
                btype = "point,line,area",
                output = "b10s",
                operator = "overlap")

    run_command("v.split",
                input = "b10s",
                layer = "-1",
                output = "b10s_s100",
                length = 100,
                units = "map")


    return 0

if __name__ == "__main__":
    options, flags = parser()
    atexit.register(cleanup)
    sys.exit(main())
