#!/usr/bin/env python
#
##############################################################################
#
# MODULE:       model
#
# AUTHOR(S):    will
#               
# PURPOSE:      Script generated by wxGUI Graphical Modeler.
#
# DATE:         Wed Jul  6 18:49:49 2016
#
##############################################################################

#%module
#% description: Script generated by wxGUI Graphical Modeler.
#%end

import sys
import os
import atexit

from grass.script import parser, run_command

def cleanup():
    pass

def main():
    run_command("r.water.outlet",
                overwrite = True,
                input = "rse_dir@will",
                output = "basin5",
                coordinates = 691577.15,4225534.21)

    run_command("r.to.vect",
                overwrite = True,
                input = "basin5",
                output = "basin5",
                type = "area",
                column = "value")

    run_command("v.overlay",
                overwrite = True,
                ainput = "rse_st@will",
                alayer = "1",
                atype = "line",
                binput = "basin5",
                blayer = "1",
                btype = "area",
                operator = "and",
                output = "bas5_st",
                olayer = "0,1,0",
                snap = 1e-8)

    run_command("v.split",
                overwrite = True,
                input = "bas5_st",
                layer = "-1",
                output = "bas5_st100",
                length = 100,
                units = "map")

    run_command("v.out.ogr",
                verbose = True,
                input = "bas5_st100",
                layer = "1",
                type = "line",
                output = "bas5st100",
                format = "ESRI_Shapefile")


    return 0

if __name__ == "__main__":
    options, flags = parser()
    atexit.register(cleanup)
    sys.exit(main())
